server:
  port: 8090

logging:
  level:
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
          jwk-set-uri: http://localhost:9090/.well-known/jwks.json
          jws-algorithms: RS256
          audiences: account
